openapi: 3.0.0
info:
  title: Deribit Account Management Supporting API
  version: 2.1.1
servers:
- url: https://test.deribit.com/api/v2
tags:
- name: Supporting
paths:
  /public/hello:
    get:
      parameters:
      - name: client_name
        in: query
        schema:
          type: string
          example: My Trading Software
        required: true
        description: Client software name
      - name: client_version
        in: query
        schema:
          type: string
          example: 1.0.2
        required: true
        description: Client software version
      responses:
        '200':
          $ref: '#/components/responses/PublicTestResponse'
      tags:
      - Supporting
      requestBody:
        content:
          application/json:
            examples:
              request:
                value:
                  jsonrpc: '2.0'
                  id: 2841
                  method: public/hello
                  params:
                    client_name: My Trading Software
                    client_version: 1.0.2
                description: JSON-RPC Request Example
        description: JSON-RPC request body
      description: 'Method used to introduce the client software connected to Deribit platform over websocket. Provided data may have an impact on the maintained connection and will be collected for internal statistical purposes. In response, Deribit will also introduce itself.


        [Try in API console](https://test.deribit.com/api_console?method=%2Fpublic%2Fhello)


        '
      x-mint:
        metadata:
          title: public/hello
          og:title: public/hello
          keywords:
          - public/hello
          - client_name
          - client_version
          - version
        href: /api-reference/supporting/public-hello
  /public/status:
    get:
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/PublicStatusResponse'
      tags:
      - Supporting
      requestBody:
        content:
          application/json:
            examples:
              request:
                value:
                  jsonrpc: '2.0'
                  id: 55
                  method: public/status
                  params: {}
                description: JSON-RPC Request Example
        description: JSON-RPC request body
      description: 'Method used to get information about locked currencies


        [Try in API console](https://test.deribit.com/api_console?method=%2Fpublic%2Fstatus)


        '
      x-mint:
        metadata:
          title: public/status
          og:title: public/status
          keywords:
          - public/status
          - locked
          - locked_indices
        href: /api-reference/supporting/public-status
  /public/test:
    get:
      parameters:
      - in: query
        name: expected_result
        required: false
        schema:
          type: string
          enum:
          - exception
        description: The value "exception" will trigger an error response. This may be useful for testing wrapper libraries.
      responses:
        '200':
          $ref: '#/components/responses/PublicTestResponse'
      tags:
      - Supporting
      requestBody:
        content:
          application/json:
            examples:
              request:
                value:
                  jsonrpc: '2.0'
                  id: 8212
                  method: public/test
                  params: {}
                description: JSON-RPC Request Example
        description: JSON-RPC request body
      description: 'Tests the connection to the API server, and returns its version. You can use this to make sure the API is reachable, and matches the expected version.


        [Try in API console](https://test.deribit.com/api_console?method=%2Fpublic%2Ftest)


        '
      x-mint:
        metadata:
          title: public/test
          og:title: public/test
          keywords:
          - public/test
          - expected_result
          - version
        href: /api-reference/supporting/public-test
  /public/get_time:
    get:
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/PublicGetTimeResponse'
      tags:
      - Supporting
      requestBody:
        content:
          application/json:
            examples:
              request:
                value:
                  jsonrpc: '2.0'
                  id: 7365
                  method: public/get_time
                  params: {}
                description: JSON-RPC Request Example
        description: JSON-RPC request body
      description: 'Retrieves the current time (in milliseconds). This API endpoint can be used to check the clock skew between your software and Deribit''s systems.


        [Try in API console](https://test.deribit.com/api_console?method=%2Fpublic%2Fget_time)


        '
      x-mint:
        metadata:
          title: public/get_time
          og:title: public/get_time
          keywords:
          - public/get_time
        href: /api-reference/supporting/public-get_time
components:
  schemas:
    PublicTestResponse:
      properties:
        jsonrpc:
          type: string
          enum:
          - '2.0'
          description: The JSON-RPC version (2.0)
        id:
          type: integer
          description: The id that was sent in the request
        result:
          type: object
          properties:
            version:
              example: 2.1.26
              type: string
              description: The API version
          required:
          - version
      required:
      - jsonrpc
      - result
      type: object
    PublicGetTimeResponse:
      properties:
        jsonrpc:
          type: string
          enum:
          - '2.0'
          description: The JSON-RPC version (2.0)
        id:
          type: integer
          description: The id that was sent in the request
        result:
          type: integer
          example: 1517329113791
          description: Current timestamp (milliseconds since the UNIX epoch)
      required:
      - jsonrpc
      - result
      type: object
    PublicStatusResponse:
      properties:
        jsonrpc:
          type: string
          enum:
          - '2.0'
          description: The JSON-RPC version (2.0)
        id:
          type: integer
          description: The id that was sent in the request
        result:
          type: object
          properties:
            locked:
              type: string
              description: '`true` when platform is locked in all currencies, `partial` when some currencies are locked, `false` - when there are not currencies locked'
            locked_indices:
              type: array
              description: List of currency indices locked platform-wise
          required:
          - locked
      required:
      - jsonrpc
      - result
      type: object
  responses:
    PublicStatusResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PublicStatusResponse'
          examples:
            response:
              value:
                jsonrpc: '2.0'
                id: 55
                result:
                  locked_currencies:
                  - BTC
                  - ETH
                  locked: true
              description: Response example
      description: Success response
    PublicGetTimeResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PublicGetTimeResponse'
          examples:
            response:
              value:
                jsonrpc: '2.0'
                id: 7365
                result: 1550147385946
              description: Response example
      description: Success response
    PublicTestResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PublicTestResponse'
          examples:
            response:
              value:
                jsonrpc: '2.0'
                id: 8212
                result:
                  version: 1.2.26
              description: Response example
      description: Success response
